---
title: 'Light-Field Imaging 101'
subtitle: 'A comprehensive introduction to unfocused light-field imaging (plenoptic 1.0)'
author: 'David Nguyen'
# date: 04/25/2025
date-modified: last-modified
date-format: 'MMMM D, YYYY'
number-sections: true
bibliography: references.bib
csl: ieee.csl
jupyter: python3
---

# Intended Audience

This guide aims to expand upon existing unfocused light-field (plenoptic 1.0) imaging learning material by providing detailed Python implementations of light-field image processing along with examples. The light-field image processing workflow closely follows that of the MATLAB-based Light-Field Imaging Toolkit [@bolan2016light], but leverages Python's open-source ecosystem and Quarto's enhanced capabilities for visualization and LaTeX formula integration.

By focusing specifically on the image processing aspects, this guide helps readers better understand the technical limitations and practical considerations of light-field imaging techniques. This guide assumes the reader is familiar with unfocused light-field imaging. Such an understanding can be achieved by browsing [plenoptic.info](https://www.plenoptic.info/) or reading the unfocused light-field part of the Light-Field Camera Working Principles chapter (Pages 11-25) of the book Development and Application of Light-Field Cameras in Fluid Measurements [@shi2023development].

# Preprocessing

## Raw Images

To illustrate light-field image processing concepts, a synthetic unfocused light-field image was generated and is shown in @fig-unfocused-light-field. The image describes the raw pixel intensities as recorded by an unfocused light-field camera. Every lenslet of the camera projects the incident radiance into a defocused intensity distribution pattern. This manifests as a spatially constrained blur where the light energy from each microlens is distributed across multiple sensor pixels rather than being concentrated at the expected conjugate position. The image was generated using a commercial ray tracing software (OpticStudio, ANSYS).

::: {#fig-unfocused-light-field .column-page style='text-align: center;'}
```{python}
import tifffile
import plotly.express as px

raw_light_field_image = tifffile.imread('127x127_mla.tif')

fig = px.imshow(
    raw_light_field_image,
    color_continuous_scale='gray',
    aspect='equal'
)
fig.update_layout(
    xaxis=dict(showticklabels=False, showgrid=False, zeroline=False, visible=False),
    yaxis=dict(showticklabels=False, showgrid=False, zeroline=False, visible=False)
)
fig.show()
```
Synthetic unfocused light-field image. The hexagonal patterning in the image is characteristic of the projection process by the microlens array.
:::

## Microlens Array Structure {#sec-mla}

The unfocused light-field camera model implemented in this investigation utilizes a hexagonal microlens array configuration for two primary reasons. First, hexagonal microlens arrays provide optimal spatial packing efficiency, thereby maximizing the effective sensor area utilization. Second, the hexagonal pattern introduces additional computational complexity in light-field image processing algorithms—specifically in sampling pattern interpolation—that merits thorough examination within this methodological framework.

The hexagonal microlens array has 127 × 127 complete lenslets. This core array is supplemented with partial lenslets along the periphery to achieve an overall rectangular shape. The total number of elements in the array is 16&thinsp;447, which corresponds to the expected number of spots in the calibration image.

## Calibration {#sec-calibration}

The calibration process seeks to pinpoint the centroid of each lenslet's corresponding sensor region. A calibration image is acquired with the main lens's aperture reduced to a minimum. The resulting calibration image consist of an array of small bright spots as shown in @fig-calibration.

::: {#fig-calibration .column-page style='text-align: center;'}
```{python}
calibration_image = tifffile.imread('127x127_ref.tif')

fig = px.imshow(
    calibration_image,
    color_continuous_scale='gray',
    aspect='equal'
)
fig.update_layout(
    xaxis=dict(showticklabels=False, showgrid=False, zeroline=False, visible=False),
    yaxis=dict(showticklabels=False, showgrid=False, zeroline=False, visible=False)
)
fig.show()
```
Synthetic light-field calibration image. Every bright spot is indicative of the corresponding lenslet centroid on the sensor.
:::

The centroid identification process based on intensity peaks in an image is a standard image processing technique widely documented in the literature, not exclusive to light-field imaging. Since the synthetic calibration image contains no sensor noise, the calibration procedure has been intentionally simplified to emphasize conceptual clarity and streamline the explanation.

The spot centroid detection procedure consists of three main steps. First, a manual threshold is applied to the calibration image to identify potential spot locations. Second, a binary dilation operation using a disk-shaped structuring element is performed to expand these areas, ensuring that the subsequent weighted centroid calculation encompasses the full spot and its immediate surroundings. Finally, the [`scikit-image`](https://scikit-image.org/) `regionprops` function is used to calculate the intensity-weighted centroids of each spot.

```{python}
#| echo: true
import numpy as np

from skimage import morphology
from skimage.morphology import disk
from skimage.measure import label, regionprops

# Load calibration image
calibration_image = tifffile.imread('127x127_ref.tif')

# Apply hard-coded threshold (chosen to match the expected number of centroids)
binary_calibration = calibration_image>8

# Perform a binary dilation to ensure coverage of the spots for the computation
# of the weighted centroid
dilated_calibration = morphology.binary_dilation(binary_calibration, disk(3))

# Create labels 
labeled_calibration = label(dilated_calibration)

# Apply regionprops
regions_calibration = regionprops(labeled_calibration, intensity_image=calibration_image)

# Retrieve weighted centroids location and convert list to numpy array
centroids = np.array([region.centroid_weighted for region in regions_calibration])

print(f'Number of centroids detected: {len(centroids):,}'.replace(',', '\u2009'))
```

The threshold value was manually selected to ensure the number of detected centroids matches the total lenslet count (16&thinsp;447) as described in @sec-mla.

The centroid localization procedure is demonstrated in @fig-centroid using a representative calibration spot. The figure displays three frames: the first showing a magnified view of an individual calibration spot, the second showing the binary mask generated through thresholding, and the third showing the binary mask after a morphological dilation operation. The calculated weighted centroid position, determined by applying the dilated mask to the original intensity distribution of the spot, is indicated by a pink cross marker.

::: {#fig-centroid .column-page style='text-align: center;'}
```{python}
import plotly.graph_objects as go

def get_roi(image, center, half_size):
    x, y = center
    return image[x-half_size:x+half_size+1, y-half_size:y+half_size+1]

one_centroid = centroids[7790]
rounded_centroid = one_centroid.astype(int)
roi_half_size = 6

calibration_roi = get_roi(calibration_image, rounded_centroid, roi_half_size)
binary_roi = get_roi(binary_calibration, rounded_centroid, roi_half_size)
dilated_roi = get_roi(dilated_calibration, rounded_centroid, roi_half_size)

fig = px.imshow(
    np.stack([calibration_roi, binary_roi, dilated_roi], axis=0),
    color_continuous_scale='gray',
    aspect='equal',
    animation_frame=0
)
fig.add_trace(
    go.Scatter(
        x=[one_centroid[1]-rounded_centroid[1]+roi_half_size],
        y=[one_centroid[0]-rounded_centroid[0]+roi_half_size],
        marker=dict(
            size=20,
            line=dict(
                width=5,
                color='#CC79A7'
            ),
            symbol='x-thin'
        )
    )
)
fig.update_layout(
    coloraxis_showscale=False,
    dragmode=False,
    xaxis=dict(
        showticklabels=False, 
        showgrid=False, 
        zeroline=False, 
        visible=False,
        fixedrange=True
    ),
    yaxis=dict(
        showticklabels=False, 
        showgrid=False, 
        zeroline=False, 
        visible=False,
        fixedrange=True
    )
)
fig['layout'].pop('updatemenus')
fig['layout']['sliders'][0]['pad']=dict(r=80, b=20)
fig.layout.sliders[0].steps[0].label = 'Calibration ROI'
fig.layout.sliders[0].steps[1].label = 'Thresholded ROI'
fig.layout.sliders[0].steps[2].label = 'Dilated ROI'
fig.show()
```
Close-up of a calibration spot showing the centroid identification process. Toggle view displays: 'Calibration ROI' (original spot from calibration image), 'Thresholded ROI' (binary mask after thresholding), or 'Dilated ROI' (binary mask after morphological dilation). Pink cross indicates the weighted centroid location calculated from the original intensity distribution using the dilated mask.
:::

## Reshaping

The next step is to reshape the 2D light-field image into a 4D light-field array as a function of U and V (the spatial coordinates), and S and T (the angular coordinates). Each centroid location from @sec-calibration has coordinates corresponding to a position in the S and T space. From this position, a circular U and V map is extracted from the light-field image for each centroid. An interpolation step is introduced to have the centroid aligned on the pixel grid. A masking operation is performed to remove information from neighbouring lenslets.

```{python}
#| echo: true
from scipy.interpolate import interpn

def get_roi(image, center, half_size):
    """
    Extract a square Region of Interest (ROI) from an image.
    
    Parameters:
    -----------
    image : ndarray
        The input image from which to extract the ROI.
    center : tuple of int
        The (x, y) coordinates of the center point of the ROI as integer indices.
    half_size : int
        Half the size of the ROI. The total width/height will be (2*half_size+1).
        
    Returns:
    --------
    ndarray
        A square sub-image centered at the specified coordinates with 
        dimensions (2*half_size+1) × (2*half_size+1).
    """
    x, y = center
    return image[x-half_size:x+half_size+1, y-half_size:y+half_size+1]

# Load raw light-field image
raw_light_field_image = tifffile.imread('127x127_mla.tif')

# Hard-coded UV map radius
uv_radius = 7

# Hard-coded margin (for interpolation)
margin = 3

# Initialize integer grid
integer_grid = np.arange(-(uv_radius+margin), uv_radius+margin+1)
u_int_grid, v_int_grid = np.meshgrid(integer_grid, integer_grid)

# Create circular mask
circular_mask = u_int_grid**2 + v_int_grid**2 <= uv_radius**2

# Initialize light-field array
uv_diameter = 2*uv_radius+1
light_field_array = np.zeros((len(centroids), uv_diameter, uv_diameter))

# Loop over the number of detected centroids
for ii, centroid in enumerate(centroids):
    # Rounded centroid location
    rounded_centroid = centroid.astype(int)

    # Calculate centroid grid offset
    offset = centroid - rounded_centroid

    # Create new grids for interpolation
    u_grid, v_grid = np.meshgrid(integer_grid+offset[0], integer_grid+offset[1])

    # Extract ROI around the centroid
    uv_roi = get_roi(raw_light_field_image, rounded_centroid, uv_radius+margin)

    # Interpolate the ROI to the offset grid
    interpolated_roi = interpn(
        (integer_grid, integer_grid),
        uv_roi,
        (v_grid, u_grid),
        bounds_error=False,
        fill_value=None
        )

    # Populate light-field array and perform masking operation (removing the margin)
    light_field_array[ii, :, :] = (interpolated_roi*circular_mask)[margin:-margin, margin:-margin]
```

The reshaping procedure is demonstrated in @fig-reshaping using a representative angular (U and V) space in the light-field image. The figure displays three frames: the first showing an angular space from the light-field image at the location of a rounded calibration spot, the second showing the same angular space interpolated at the exact location of the centroid (aligned with the pixel grid), and the third showing the circular masking to reject angular information from neighboring lenslets. The pink cross marker indicates the weighted centroid position. Yellow axes indicate the center of the ROI.

::: {#fig-reshaping .column-page style='text-align: center;'}
```{python}
from scipy.interpolate import interpn

one_centroid = centroids[7790]
rounded_centroid = one_centroid.astype(int)

roi_half_size = 10

one_uv = get_roi(raw_light_field_image, rounded_centroid, roi_half_size)

old_u = np.arange(-roi_half_size, roi_half_size+1)
old_v = np.arange(-roi_half_size, roi_half_size+1)

new_u = old_u + (one_centroid[0] - rounded_centroid[0])
new_v = old_v + (one_centroid[1] - rounded_centroid[1])

new_u_grid, new_v_grid = np.meshgrid(new_u, new_v)

interpolated_uv = interpn((old_u, old_v), one_uv, (new_u_grid, new_v_grid), bounds_error=False, fill_value=None)

old_u_grid, old_v_grid = np.meshgrid(old_u, old_v)
mask = old_u_grid**2 + old_v_grid**2 <= uv_radius**2

offset_centroid = one_centroid-rounded_centroid+roi_half_size

fig = px.imshow(
    np.stack([one_uv, interpolated_uv, interpolated_uv*mask], axis=0),
    color_continuous_scale='gray',
    aspect='equal',
    animation_frame=0
)
fig.frames[0].data = fig.frames[0].data + (go.Scatter(
    x=[offset_centroid[1]],
    y=[offset_centroid[0]],
    mode='markers',
    marker=dict(
        size=20,
        line=dict(width=5, color='#CC79A7'),
        symbol='x-thin'
    ),
    showlegend=False
),)
fig.frames[1].data = fig.frames[1].data + (go.Scatter(
    x=[roi_half_size],
    y=[roi_half_size],
    mode='markers',
    marker=dict(
        size=20,
        line=dict(width=5, color='#CC79A7'),
        symbol='x-thin'
    ),
    showlegend=False
),)
fig.add_trace(go.Scatter(
    x=[offset_centroid[1]],
    y=[offset_centroid[0]],
    mode='markers',
    marker=dict(
        size=20,
        line=dict(width=5, color='#CC79A7'),
        symbol='x-thin'
    ),
    showlegend=False
))
fig.add_shape(
    type='line',
    x0=0,
    y0=roi_half_size,
    x1=2*roi_half_size,
    y1=roi_half_size,
    line=dict(
        color='#F0E442',
        width=2
    )
)
fig.add_shape(
    type='line',
    x0=roi_half_size,
    y0=0,
    x1=roi_half_size,
    y1=2*roi_half_size,
    line=dict(
        color='#F0E442',
        width=2
    )
)
fig.update_layout(
    coloraxis_showscale=False,
    dragmode=False,
    xaxis=dict(
        showticklabels=False, 
        showgrid=False, 
        zeroline=False, 
        visible=False,
        fixedrange=True
    ),
    yaxis=dict(
        showticklabels=False, 
        showgrid=False, 
        zeroline=False, 
        visible=False,
        fixedrange=True
    )
)
fig['layout'].pop('updatemenus')
fig['layout']['sliders'][0]['pad']=dict(r=80, b=20)
fig.layout.sliders[0].steps[0].label = 'UV Map From ROI'
fig.layout.sliders[0].steps[1].label = 'Interpolated UV Map'
fig.layout.sliders[0].steps[2].label = 'Masked UV Map'
fig.show()
```
Close-up of a light-field angular (U, V) map showing the reshaping process. Toggle view displays: 'UV Map From ROI' (original angular space from light-field image at a specific lenslet location), 'Interpolated UV Map' (angular space with centroid aligned to pixel grid at the center of the close-up), or 'Masked UV Map' (circular mask applied to retain only information from the corresponding lenslet). Pink cross indicates the weighted centroid location. Yellow axes indicate the center of the ROI.
:::



```{python}
from scipy.interpolate import griddata

grid_size = 127

hex_grid = centroids[:, [1, 0]]

x_grid_min, x_grid_max = np.min(hex_grid[:, 0]), np.max(hex_grid[:, 0])
y_grid_min, y_grid_max = np.min(hex_grid[:, 1]), np.max(hex_grid[:, 1])
    
grid_x = np.linspace(x_grid_min, x_grid_max, grid_size)
grid_y = np.linspace(y_grid_min, y_grid_max, grid_size)
grid_xx, grid_yy = np.meshgrid(grid_x, grid_y)

all_grids = []
for aperture_half_size in range(8):
    square_grid = griddata(
        hex_grid,
        np.sum(light_field_array[:, 7-aperture_half_size:8+aperture_half_size, 7-aperture_half_size:8+aperture_half_size], axis=(1, 2)),
        (grid_xx, grid_yy),
        method='linear',
        fill_value=0
    )
    all_grids.append(square_grid)

fig = go.Figure()
fig.add_trace(go.Heatmap(z=all_grids[0], colorscale='gray', showscale=False))

frames = []
for i, grid in enumerate(all_grids):
    frames.append(go.Frame(data=[go.Heatmap(z=grid, colorscale='gray', showscale=False)], name=str(i)))
fig.frames = frames

sliders = [{
    'active': 0,
    'currentvalue': {'prefix': 'Aperture Half Size: '},
    'pad': {'t': 50},
    'steps': [
        {
            'method': 'animate',
            'args': [[str(i)], {'frame': {'duration': 0, 'redraw': True}, 'mode': 'immediate', 'transition': {'duration': 0}}],
            'label': str(i)
        } for i in range(8)
    ]
}]

fig.update_layout(
    sliders=sliders,
    xaxis=dict(showticklabels=False, showgrid=False, zeroline=False, visible=False),
    yaxis=dict(autorange='reversed', showticklabels=False, showgrid=False, zeroline=False, visible=False),
    width=600,
    height=600
)

fig.show()
```



```{python}
numS = 127
numT = 127
numU = 21
numV = 21

focus_array = np.zeros((numU*numV, numS, numT))
```